// Package pac generates proxy auto-configuration files.
//
// Browsers and OS proxy settings are usually pointed at a PAC URL rather than a
// host and port, so serving one means clients are configured once and routed
// centrally afterwards.
//
// The file is generated from live configuration on every request rather than
// written once, because a PAC that has drifted from the policy is worse than
// none: clients would be routed by a document nobody is looking at.
package pac

import (
	"fmt"
	"net"
	"net/http"
	"strings"

	"github.com/pod32g/proxy/internal/policy"
)

// ContentType is what a PAC file is served as. Browsers are lenient about it,
// but some OS-level proxy configurators are not.
const ContentType = "application/x-ns-proxy-autoconfig"

// Path is where the file is served.
const Path = "/proxy.pac"

// Config is what a generated file needs.
type Config struct {
	// Address is the host:port clients should send traffic to. Not necessarily
	// the proxy's own bind address: behind NAT or a load balancer, and for
	// anything bound to 0.0.0.0, the bind address is not something a client can
	// use.
	Address string

	// HintDirect adds DIRECT hints for destinations the proxy would refuse and
	// for the parent-proxy bypass list, so clients skip round trips that could
	// only fail.
	//
	// Off unless asked for, and separate from serving the file at all, because
	// this is the part that discloses: a deny list is a map of an
	// organisation's internal naming, and the file is served unauthenticated by
	// necessity — a browser fetches it before it has anywhere to send
	// credentials.
	HintDirect bool

	// Rules and Bypass supply the hints. Ignored unless HintDirect.
	Rules  *policy.RuleSet
	Bypass []string
}

// Generate renders the PAC file.
func Generate(cfg Config) string {
	var b strings.Builder

	b.WriteString("// Generated by the proxy from its live configuration.\n")
	b.WriteString("// Do not edit: this is regenerated on every request.\n")
	b.WriteString("function FindProxyForURL(url, host) {\n")

	if cfg.HintDirect {
		b.WriteString(directHints(cfg))
	}

	// The fallback to DIRECT matters: a client whose proxy is unreachable
	// should degrade to a direct attempt rather than fail closed with no
	// network at all, which is what a bare "PROXY host:port" produces when the
	// proxy is down.
	fmt.Fprintf(&b, "  return \"PROXY %s; DIRECT\";\n", jsEscape(cfg.Address))
	b.WriteString("}\n")
	return b.String()
}

// directHints renders the opt-in DIRECT rules.
func directHints(cfg Config) string {
	var b strings.Builder
	seen := map[string]bool{}

	emit := func(line string) {
		if !seen[line] {
			seen[line] = true
			b.WriteString(line)
		}
	}

	// Loopback and the machine's own name are always direct. Sending them
	// through a proxy is a round trip that cannot succeed, and every PAC in the
	// world starts this way.
	emit("  if (isPlainHostName(host) || shExpMatch(host, \"localhost\")) return \"DIRECT\";\n")
	emit("  if (isInNet(host, \"127.0.0.0\", \"255.0.0.0\")) return \"DIRECT\";\n")

	for _, entry := range cfg.Bypass {
		entry = strings.TrimSpace(entry)
		if entry == "" || entry == "*" {
			continue
		}
		if _, network, err := net.ParseCIDR(entry); err == nil {
			emit(fmt.Sprintf("  if (isInNet(host, %q, %q)) return \"DIRECT\";\n",
				network.IP.String(), net.IP(network.Mask).String()))
			continue
		}
		host := strings.TrimPrefix(entry, ".")
		emit(fmt.Sprintf("  if (dnsDomainIs(host, %q) || host == %q) return \"DIRECT\";\n",
			"."+host, host))
	}

	// Destinations the policy refuses cannot be fetched through the proxy, so
	// routing a client to it only produces a 403 after a round trip.
	//
	// Only leading denials are emitted. A deny that sits after an allow may be
	// unreachable for a given host, and a PAC has no way to express "unless an
	// earlier rule matched" — emitting it anyway would send a client direct to
	// somewhere the proxy would have allowed.
	if cfg.Rules != nil {
		for _, rule := range cfg.Rules.Rules {
			if rule.Action != policy.Deny {
				break
			}
			switch rule.Kind {
			case policy.KindDomain:
				pattern := rule.Value
				if suffix, ok := strings.CutPrefix(pattern, "*."); ok {
					emit(fmt.Sprintf("  if (dnsDomainIs(host, %q)) return \"DIRECT\";\n", "."+suffix))
					continue
				}
				emit(fmt.Sprintf("  if (dnsDomainIs(host, %q) || host == %q) return \"DIRECT\";\n",
					"."+pattern, pattern))
			case policy.KindCIDR:
				if rule.Network() != nil {
					n := rule.Network()
					emit(fmt.Sprintf("  if (isInNet(host, %q, %q)) return \"DIRECT\";\n",
						n.IP.String(), net.IP(n.Mask).String()))
				}
			case policy.KindAll:
				// "deny all" first means nothing is proxyable, which a PAC can
				// say plainly.
				emit("  return \"DIRECT\";\n")
			}
		}
	}
	return b.String()
}

// jsEscape neutralises anything that could break out of the string literal it
// lands in. The address comes from configuration rather than a request, but a
// generated program should not be one quoting mistake away from arbitrary
// script running in every client that fetches it.
func jsEscape(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r < 0x20 || r == 0x7f:
			fmt.Fprintf(&b, "\\u%04x", r)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// Handler serves the PAC file, regenerating it per request so it cannot drift
// from the configuration it describes.
//
// config is a function for the same reason: policy changes at runtime through
// the UI, the API and SIGHUP, and a handler holding a snapshot would serve a
// file describing a configuration that stopped being true.
func Handler(config func() Config) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			http.Error(w, "the PAC file is read-only", http.StatusMethodNotAllowed)
			return
		}
		body := Generate(config())
		w.Header().Set("Content-Type", ContentType)
		w.Header().Set("Content-Length", fmt.Sprint(len(body)))
		// Clients cache PAC files aggressively, and a stale one routes traffic
		// by a policy that no longer exists.
		w.Header().Set("Cache-Control", "no-store")
		w.WriteHeader(http.StatusOK)
		if r.Method == http.MethodGet {
			_, _ = w.Write([]byte(body))
		}
	})
}

// Advertisable reports whether an address is one a client could actually use,
// and why not when it is not.
//
// A PAC advertising 0.0.0.0 or an empty host is a file that cannot work, and it
// fails at the client with no clue pointing back here. Better to say so at
// startup.
func Advertisable(addr string) (bool, string) {
	host, port, err := net.SplitHostPort(addr)
	if err != nil {
		return false, fmt.Sprintf("%q is not host:port", addr)
	}
	if port == "" {
		return false, "no port"
	}
	if host == "" {
		return false, "no host: a PAC file has to name an address clients can reach"
	}
	if ip := net.ParseIP(host); ip != nil {
		if ip.IsUnspecified() {
			return false, fmt.Sprintf("%s is a wildcard bind address, not something a client can connect to", host)
		}
	}
	return true, ""
}
